### PR TITLE
fix: make ControlledSelect testable

### PR DESCRIPTION
**Pull request by luizprsjr**
## What does this do?

Makes the ControlledSelect easier to test within forms.

## Why did you do this?

I was creating a signup screen where the user should choose their account type using a select, either "user" or "trucker", but my tests couldn't interact with the BottomSheetFlatList inside the ControlledSelect because the options list was not appearing.

## Who/what does this impact?

.

## How did you test this?

This was the first test I conducted, and I couldn't get it to pass before the changes. I subsequently conducted more complex tests, which also worked, but sharing them here wouldn't add much value.

```tsx
<ControlledSelect
  control={control}
  name="type"
  options={userTypeOptions}
  label="Tipo da conta"
  placeholder="Selecione..."
/>
```

```tsx
it('should render the correct select options and select a type', async () => {
    const { getByTestId, getByText, queryByText } = render(<SignUpForm />);
    expect(queryByText(/Selecione.../i)).not.toBeNull();
    const select = getByText('Selecione...');
    fireEvent.press(select);

    const truckerOption = getByText('Caminhoneiro');
    const userOption = getByText('Usuário');
    expect(truckerOption).toBeTruthy();
    expect(userOption).toBeTruthy();
    fireEvent.press(truckerOption);

    const button = getByTestId('sign-up-button');
    expect(button).toBeTruthy();
    fireEvent.press(button);

    expect(queryByText(/Selecione.../i)).toBeNull();
  });
```

### CODE REVIEW

**Comment by yjose** [comment]
Hey @luizprsjr thank you for bringing that. I am a little bit confusing but if you look at [mock.js](https://github.com/gorhom/react-native-bottom-sheet/blob/65b5dc03e673c25b3b41af954e1f13fe7668a339/mock.js#L2)  you will noticed that `BottomFlatList` is already mocked as `FlatList` 🤔

**Comment by luizprsjr** [comment]
I just reviewed the code, and it appears that a commit was made to the library four months ago to address the issue with mocks. It's possible that the library version in the template is outdated, leading to the problem we encountered. Please consider updating the library version in the template to the latest one to ensure that this issue is resolved. You can refer to the following pull request for more information: [link](https://github.com/gorhom/react-native-bottom-sheet/pull/1394).

**Comment by luizprsjr** [comment]
I have opened a new pull request for update [#232](https://github.com/obytes/react-native-template-obytes/pull/232)

**Comment by yjose** [comment]
Thank you @luizprsjr for your investigation, can you confirm that updating the library fixes the issue related to mocking? 

in this case we can close this PR and merge #232

**Comment by luizprsjr** [comment]
Yes @yjose, I reverted to the original mock and updated the library, and all the tests passed.

**Comment by yjose** [comment]
closed in favor of #232

**Pull request closed without merging**
