### PR TITLE
Feat: add native wind web support

### PR DESCRIPTION
**Pull request by 0x10Ayoub**
## What does this do?

add native wind web support 

## How did you test this?

Manually

### CODE REVIEW

**Review by yjose — CHANGES_REQUESTED** [review]
I am seeing a bunch of warning while running the web command
image
Also please make sure to add the web command to package.json  `"web": "expo start --web"`. 

Can you please  also make sure we are disabling the dark mode on the web as we are not fully supporting it with our ui

**Comment by 0x10Ayoub** [comment]
for expo-image i think  the error is  from the package itself  https://github.com/expo/expo/issues/21846
The same for  mmkv in the package files has src as their target  sourceRoot but doesn't get published with the package https://github.com/mrousavy/react-native-mmkv/issues/516

**Comment by yjose** [comment]
@0x10Ayoub  He mention that mmkv issue has been fixed with the version 2.8.0 but we are still using  2.6 in the project

**Comment by 0x10Ayoub** [comment]
@yjose  yes i did test 2.8.0 still same issue

**Comment by yjose** [comment]
In this case let wait the two fixes before merging the PR

**Comment by tonven** [comment]
@0x10Ayoub @yjose Hi. Any plans of merging this one? 😀

**Comment by 0x10Ayoub** [comment]
> @0x10Ayoub @yjose Hi. Any plans of merging this one? 😀

soon in 2 weeks

**Comment by 0x10Ayoub** [comment]
webpack deprecated in favor of metro in expo SDK +50 
https://blog.expo.dev/webpack-support-in-expo-cli-is-now-deprecated-e9831d7eb631
it's better to start over rather than continue working on this pr

**Comment by yjose** [comment]
@0x10Ayoub a migration to nativewind v4 is coming soon along with the expo router. we think this migration will come up with web support by default

**Pull request closed without merging**
